- name: download node exporter
  ansible.builtin.unarchive:
    src: "{{ exporter_url }}"
    dest: /opt
    remote_src: true

- name: update systemd file
  ansible.builtin.template:
    src: exporter.service
    dest: /etc/systemd/system/node_exporter.service