- name: copying systemd templates
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: enable and restart service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: true
    daemon-reload: true
