groups:
- name: Roboshop
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: Server down
    expr: up < 1
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: sever down

  - alert: CPU utilization
    expr: 100 - (avg by (name) (rate(node_cpu_seconds_total{mode="idle"}[1m]))*100) > 80
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: CPU utilization is high